# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  database: memamoru_development
  username: root
  password: 
  encoding: utf8
  pool: 5
  timeout: 5000