development:
  FACEBOOK_KEY: "139765763105959"
  FACEBOOK_SECRET: "dc58e04a29f729ae80a238bb0190a5a2"
  
  GOOGLE_KEY: "727562097600-hrikv01cdjot8tr3aa69dinv5m8k6bp2.apps.googleusercontent.com"
  GOOGLE_SECRET: "o-qI8KPNdDmEN8-MhB4FdV5V"

  TWITTER_KEY: "q0XgrSlUNQtP19abYGELpyAoP"
  TWITTER_SECRET: "QDlFWumTv1Kjp4DqIDQyVtWEXU6iVqqsgZJg2zWkJ1JVEPsxf1"

  YAHOOJP_KEY: "dj0zaiZpPVp5SDRqMHMwbTZlYSZzPWNvbnN1bWVyc2VjcmV0Jng9MmU-"
  YAHOOJP_SECRET: "09571b89ffef9bf476ea934ab70ed1e4d013abbb"

production:
  FACEBOOK_KEY: "139765763105959"
  FACEBOOK_SECRET: "dc58e04a29f729ae80a238bb0190a5a2"  

  GOOGLE_KEY: "727562097600-682bij363rpcpq04dk8nbv692ujo0i4l.apps.googleusercontent.com"
  GOOGLE_SECRET: "1lh4wmpAgaYYriT-B456jE6z"
  
  TWITTER_KEY: "EsDrDckzeE9YK6pzDU93Emshz"
  TWITTER_SECRET: "GJyWZXaBDjudQgcbEUhD4ysVxifze1QizUEUgFPhFBoa1r5m7l"

  YAHOOJP_KEY: "dj0zaiZpPVp5SDRqMHMwbTZlYSZzPWNvbnN1bWVyc2VjcmV0Jng9MmU-"
  YAHOOJP_SECRET: "09571b89ffef9bf476ea934ab70ed1e4d013abbb"
